// Ref: https://github.com/microsoft/TypeScript/issues/11781
/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="es2020" />
/// <reference lib="webworker" />
declare let self: ServiceWorkerGlobalScope

import { build, files, version } from '$service-worker'

const CACHE_PREFIX = 'regneflyt-app-cache'
const CACHE_SCHEMA_VERSION = 'v1'
const APP_CACHE = `${CACHE_PREFIX}-${CACHE_SCHEMA_VERSION}-${version}`
const LEGACY_APP_CACHE_PREFIX = 'app-cache-'
const APP_SHELL_URL = '/'
const OFFLINE_URL = '/offline.html'
const ROLLBACK_CACHE_SLOTS = 1
const CACHE_METADATA_CACHE = `${CACHE_PREFIX}-meta-${CACHE_SCHEMA_VERSION}`
const CACHE_METADATA_KEY_PREFIX = '/__cache_meta__/'

// `build` is an array of all the files generated by the bundler,
// `files` is an array of everything in the `static` directory
const toCache = [...build, ...files, APP_SHELL_URL]
const staticAssets = new Set(toCache)

function isVersionedAppCacheName(key: string): boolean {
	return key.startsWith(`${CACHE_PREFIX}-${CACHE_SCHEMA_VERSION}-`)
}

function shouldKeepCache(
	key: string,
	recencySortedVersionedCaches: string[]
): boolean {
	if (key === APP_CACHE) return true
	if (!isVersionedAppCacheName(key)) return false

	const rollbackCandidates = recencySortedVersionedCaches.filter(
		(name) => name !== APP_CACHE
	)
	const keepRollback = rollbackCandidates.slice(0, ROLLBACK_CACHE_SLOTS)

	return keepRollback.includes(key)
}

async function readCacheActivatedAt(
	metadataCache: Cache,
	cacheName: string
): Promise<number | undefined> {
	const metadataKey = `${CACHE_METADATA_KEY_PREFIX}${cacheName}`
	const cached = await metadataCache.match(metadataKey)
	if (!cached) return undefined

	try {
		const payload = (await cached.json()) as { activatedAt?: number }
		if (typeof payload.activatedAt === 'number') return payload.activatedAt
	} catch {
		return undefined
	}

	return undefined
}

async function writeCacheActivatedAt(
	metadataCache: Cache,
	cacheName: string,
	activatedAt: number
) {
	const metadataKey = `${CACHE_METADATA_KEY_PREFIX}${cacheName}`
	await metadataCache.put(
		metadataKey,
		new Response(JSON.stringify({ activatedAt }), {
			headers: { 'content-type': 'application/json' }
		})
	)
}

function isValidCachedStaticAsset(response: Response): boolean {
	return response.ok || response.type === 'opaque'
}

self.addEventListener('install', (event) => {
	event.waitUntil(
		(async () => {
			const cache = await caches.open(APP_CACHE)
			await cache.addAll(toCache)
		})()
	)
})

self.addEventListener('message', (event) => {
	const data: unknown = event.data
	if (
		typeof data === 'object' &&
		data !== null &&
		'type' in data &&
		(data as { type?: unknown }).type === 'SKIP_WAITING'
	) {
		void self.skipWaiting()
	}
})

self.addEventListener('activate', (event) => {
	event.waitUntil(
		(async () => {
			const keys = await caches.keys()
			const versionedAppCaches = keys.filter(isVersionedAppCacheName)
			const metadataCache = await caches.open(CACHE_METADATA_CACHE)
			const activatedAtByCache = new Map<string, number>()

			for (const cacheName of versionedAppCaches) {
				const activatedAt = await readCacheActivatedAt(metadataCache, cacheName)
				if (activatedAt !== undefined) {
					activatedAtByCache.set(cacheName, activatedAt)
				}
			}

			const recencySortedVersionedCaches = [...versionedAppCaches].sort(
				(a, b) => {
					const byTimestamp =
						(activatedAtByCache.get(b) ?? 0) - (activatedAtByCache.get(a) ?? 0)
					if (byTimestamp !== 0) return byTimestamp
					return b.localeCompare(a)
				}
			)

			// Migration policy:
			// 1) Keep current cache.
			// 2) Keep one rollback cache slot from current schema.
			// 3) Remove legacy and stale app caches.
			for (const key of keys) {
				const isLegacyAppCache = key.startsWith(LEGACY_APP_CACHE_PREFIX)
				const isVersionedAppCache = isVersionedAppCacheName(key)
				const isManagedAppCache = isLegacyAppCache || isVersionedAppCache

				if (
					isManagedAppCache &&
					!shouldKeepCache(key, recencySortedVersionedCaches)
				) {
					await caches.delete(key)
				}
			}

			try {
				await writeCacheActivatedAt(metadataCache, APP_CACHE, Date.now())
			} catch {
				// Ignore metadata write failures; activation should proceed.
			}

			await self.clients.claim()
		})()
	)
})

self.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET' || event.request.headers.has('range'))
		return

	const url = new URL(event.request.url)

	// don't try to handle e.g. data: URIs
	const isHttp = url.protocol.startsWith('http')
	const isSameOrigin = url.origin === self.location.origin
	const isDevServerRequest =
		url.hostname === self.location.hostname && url.port !== self.location.port
	const isStaticAsset =
		url.host === self.location.host && staticAssets.has(url.pathname)
	const skipBecauseUncached =
		event.request.cache === 'only-if-cached' && !isStaticAsset

	if (!isHttp || !isSameOrigin || isDevServerRequest || skipBecauseUncached)
		return

	if (event.request.mode === 'navigate') {
		event.respondWith(
			(async () => {
				try {
					return await fetch(event.request)
				} catch {
					return (
						(await caches.match(APP_SHELL_URL)) ??
						(await caches.match(OFFLINE_URL)) ??
						Response.error()
					)
				}
			})()
		)
		return
	}

	if (isStaticAsset) {
		event.respondWith(
			(async () => {
				const cached = await caches.match(event.request)
				if (cached && isValidCachedStaticAsset(cached)) return cached

				if (cached && !isValidCachedStaticAsset(cached)) {
					const cache = await caches.open(APP_CACHE)
					await cache.delete(event.request)
				}

				try {
					const response = await fetch(event.request)
					if (response.ok) {
						const cache = await caches.open(APP_CACHE)
						await cache.put(event.request, response.clone())
					}
					return response
				} catch {
					return Response.error()
				}
			})()
		)
		return
	}

	event.respondWith(
		(async () => {
			try {
				return await fetch(event.request)
			} catch {
				return (await caches.match(event.request)) ?? Response.error()
			}
		})()
	)
})
